---
- name: Install Zabbix Repository CentOS
  yum: 
    name: https://repo.zabbix.com/zabbix/{{ zabbix_release }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Install Zabbix Agent CentOS
  yum:
    name: zabbix-agent2
    state: latest

- name: Copy template zabbix-agent.conf CentOS
  template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf 

- name: Start service CentOS
  service: name=zabbix-agent2 state=restarted enabled=yes
...