---
- name: Install Zabbix Repository CentOS
  yum: 
    name: https://repo.zabbix.com/zabbix/5.4/rhel/{{ centos_version }}/x86_64/{{ zabbix_release }}.el{{ centos_version }}.noarch.rpm
    state: present

- name: Install Zabbix Agent CentOS
  yum:
    name: "{{ zabbix_agent_package }}"
    state: latest

- name: Copy template zabbix-agent.conf CentOS
  template:
    src: zabbix_agent.conf.j2
    dest: /etc/zabbix/{{zabbix_agent_package | replace ('-','_')}}.conf 

- name: Start service CentOS
  service: name="{{ zabbix_agent_package }}" state=restarted  enabled=yes
...